version: '3.9'

services:
  backend_postgres:
    container_name: backend_postgres
    image: postgres:latest
    hostname: postgres
    # restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: customer
    ports:
      - "5432:5432"