version: '3.7'
services:
  minio1:
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    volumes:
      - data1-1:/data1
      - data1-2:/data2
    ports:
      - "127.0.0.1:9000:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_SITE_REGION: "us-west-0"
    command: server data1
volumes:
  data1-1:
  data1-2: