[workspace]
members = [
    "app-error",
    "djmxcreation_backend",
    "djmxcreation-backend-axum",
    "repository",
    "app-domain",
    "app-service",
    "migration",
    "test-util",
    "app_core",
    "app_config",
]
