[workspace]
members = [
    "crates/app-error",
    "crates/djmxcreation-backend-axum",
    "crates/repository",
    "crates/app-service",
    "crates/migration",
    "crates/test-util",
    "crates/app_core",
    "crates/app_config",
]
