GET http://127.0.0.1:8080/me


### create a todo
PATCH  http://127.0.0.1:8080/me/1
content-type: application/json

{
  
  "firstName": "Judicael2",
  "lastName": "dubray3",
  "description":{

  "firstName": "caca",
  "id": 1,
  "lastName": "boo"
}

}


### create a todo
POST  http://127.0.0.1:8080/me
content-type: application/json

{
  "description": "tata",
  "firstName": "Judicael",
  "lastName": "dubray",
  "picture": "tata"
}

### create a todo
DELETE   http://127.0.0.1:8080/me/1/photo