GET http://127.0.0.1:8081/api/v1/me


### create a todo
PUT  http://127.0.0.1:8081/api/v1/me/4
content-type: application/json

{
  
  "firstName": "Judicael",
  "lastName": "dubray",
  "description":{

  "firstName": "daim",
  "id": 1,
  "lastName": "boom"
}

}


### create a todo
POST  http://127.0.0.1:8080/me
content-type: application/json

{
  "description": "tata",
  "firstName": "Judicael",
  "lastName": "dubray",
  "picture": "tata"
}

### create a todo
DELETE   http://127.0.0.1:8081/api/v1/me/4/photo