version: '3.9'

services:
  backend_minio:
    container_name: backend_minio
    image: minio/minio:latest
    restart: always
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_SITE_REGION: "us-west-0"
    command: server data1

    ports:
      - "9000:9000"