version: '3.9'

services:
  backend_rustfs:
      image: rustfs/rustfs:latest
      restart: always
      networks:
      - my-network
      container_name: backend_rustfs
      ports:
        - "9000:9000"
        - "9001:9001"
      volumes:
        - rustfs_data:/data
        - rustfs_logs:/logs
  backend_postgres:
      image: postgres:latest
      hostname: postgres
      networks:
      - my-network
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: customer
      ports:
        - "5432:5432"
  djmxcreation-backend-axum:
    build:
      context: ../..
      dockerfile: Dockerfile
    networks:
      - my-network
    ports:
      - '8080:8080'
    environment:
      PG_HOST: "postgres"
      PG_DB: "customer"
      PG_USER: "postgres"
      PG_PASSWORD: "postgres"
      PG_APP_MAX_CON: 5
      STORAGE_ENDPOINT: "http://backend_rustfs:9000"
      PORT: "8080"
      STORAGE_ACCESS_KEY: "rustfsadmin"
      STORAGE_SECRET_KEY: "rustfsadmin"
      STORAGE_REGION: "us-east-1"
      STORAGE_BUCKET: "portfolio"
      USERNAME_APP: "tata"
      PASSWORD_APP: "yoyo"
    depends_on:
      - backend_postgres
      - backend_rustfs

volumes:
  rustfs_data:
  rustfs_logs:

networks:
  my-network:
