[package]
name = "test-util"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
app_config = { path = "../app_config" }
rustainers = "0.14.0"

[lib]
name = "test_util"
path = "src/lib.rs"
