version: '3'
services:
  postgres:
    image: "postgres" 
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: customer
    # env_file:
    #   - database.env # configure postgres
    # volumes:
    #   - ./database-data:/var/lib/postgresql/data/ 
    ports:
      - "127.0.0.1:5433:5432"