version: "3"
services:
  postgres:
    image: "docker.io/library/postgres:latest"
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portfolio
    # env_file:
    #   - database.env # configure postgres
    # volumes:
    #   - ./database-data:/var/lib/postgresql/data/
    ports:
      - "127.0.0.1:5432:5432"
